### ISSUE TITLE
Refactor: utils.py

### ISSUE THREAD

**Issue by s1m0000n** [s1m0000n/multitask-transformers#6]
Fix this:

utils.py:80:0: C0304: Final newline missing (missing-final-newline)
utils.py:80:0: C0301: Line too long (101/100) (line-too-long)
utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
utils.py:1:0: W0401: Wildcard import typing (wildcard-import)
utils.py:5:0: C0103: Class name "T" doesn't conform to PascalCase naming style (invalid-name)
utils.py:10:0: C0103: Class name "attr" doesn't conform to PascalCase naming style (invalid-name)
utils.py:10:0: R0903: Too few public methods (1/2) (too-few-public-methods)
utils.py:21:0: C0103: Class name "method" doesn't conform to PascalCase naming style (invalid-name)
utils.py:21:0: R0903: Too few public methods (1/2) (too-few-public-methods)
utils.py:32:0: C0103: Class name "subcls" doesn't conform to PascalCase naming style (invalid-name)
utils.py:37:8: C0103: Attribute name "t" doesn't conform to snake_case naming style (invalid-name)
utils.py:32:0: R0903: Too few public methods (1/2) (too-few-public-methods)
utils.py:61:0: C0116: Missing function or method docstring (missing-function-docstring)
utils.py:70:4: C0103: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
utils.py:71:4: R1705: Unnecessary "else" after "return" (no-else-return)
utils.py:72:38: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
utils.py:80:33: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
utils.py:1:0: W0614: Unused import(s) collections, contextlib, functools, operator, stdlib_re, sys, types, NoReturn, ClassVar, Final, Union, Literal, ForwardRef, Generic, EXCLUDED_ATTRIBUTES, Protocol, Annotated, runtime_checkable, cast, get_type_hints, get_origin, get_args, no_type_check, no_type_check_decorator, overload, final, KT, VT, T_co, V_co, VT_co, T_contra, CT_co, AnyStr, Hashable, Awaitable, Coroutine, AsyncIterable, AsyncIterator, Iterable, Iterator, Reversible, Sized, Container, Collection, Callable, AbstractSet, MutableSet, Mapping, MutableMapping, Sequence, MutableSequence, ByteString, Tuple, List, Deque, Set, FrozenSet, MappingView, KeysView, ItemsView, ValuesView, ContextManager, AsyncContextManager, Dict, DefaultDict, OrderedDict, Counter, ChainMap, Generator, AsyncGenerator, Type, SupportsInt, SupportsFloat, SupportsComplex, SupportsBytes, SupportsIndex, SupportsAbs, SupportsRound, NamedTupleMeta, NamedTuple, TypedDict, NewType, Text, TYPE_CHECKING, IO, BinaryIO, TextIO, io, Pattern, Match, re, abstractmethod, ABCMeta, WrapperDescriptorType, MethodWrapperType, MethodDescriptorType and GenericAlias from wildcard import of typing (unused-wildcard-import)

**Comment by s1m0000n** [comment]
# To-do for utils.py

- [ ] utils.py:80:0: C0304: Final newline missing (missing-final-newline)
- [ ] utils.py:80:0: C0301: Line too long (101/100) (line-too-long)
- [ ] utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
- [ ] utils.py:1:0: W0401: Wildcard import typing (wildcard-import)
- [ ] utils.py:5:0: C0103: Class name "T" doesn't conform to PascalCase naming style (invalid-name)
- [ ] utils.py:10:0: C0103: Class name "attr" doesn't conform to PascalCase naming style (invalid-name)
- [ ] utils.py:10:0: R0903: Too few public methods (1/2) (too-few-public-methods)
- [ ] utils.py:21:0: C0103: Class name "method" doesn't conform to PascalCase naming style (invalid-name)
- [ ] utils.py:21:0: R0903: Too few public methods (1/2) (too-few-public-methods)
- [ ] utils.py:32:0: C0103: Class name "subcls" doesn't conform to PascalCase naming style (invalid-name)
- [ ] utils.py:37:8: C0103: Attribute name "t" doesn't conform to snake_case naming style (invalid-name)
- [ ] utils.py:32:0: R0903: Too few public methods (1/2) (too-few-public-methods)
- [ ] utils.py:61:0: C0116: Missing function or method docstring (missing-function-docstring)
- [ ] utils.py:70:4: C0103: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
- [ ] utils.py:71:4: R1705: Unnecessary "else" after "return" (no-else-return)
- [ ] utils.py:72:38: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
- [ ] utils.py:80:33: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
- [ ] utils.py:1:0: W0614: Unused import(s)

**Comment by s1m0000n** [comment]
Done.
